(WIP) Feature: SVG Sprite
alleyinteractive/wp-asset-manager pull request #23
Opened 2021-10-02 00:52 UTC by goodguyry

This adds support for defining SVG assets to be added to a sprite sheet.

- [ ] Allow replacing/modifying defined assets
- [ ] Add tests
- [ ] Test manually

2021-10-07 01:17 UTC, goodguyry commented on README.md
>    * [Enqueue Options](#enqueue-options)
Preview at [feature/svg-sprite/README.md#svg-sprite](https://github.com/alleyinteractive/wp-asset-manager/blob/feature/svg-sprite/README.md#svg-sprite)

2021-10-13 19:34 UTC, kjbenk requested changes
Escaping the SVG data is my only blocker, but I also provided non-blocking feedback for other things :)

2021-10-13 19:34 UTC, kjbenk commented on README.md
> +am_define_symbol(
Should we document any specific action for this to be called within? i.e. `init`

2021-10-13 19:34 UTC, kjbenk commented on README.md
> +The [wp_body_open()](https://developer.wordpress.org/reference/functions/wp_body_open/) function is required for the sprite sheet to print to the template.
Does this mean the function needs to be executed in the theme code, or that code needs to be added in the `wp_body_open` action?

2021-10-13 19:34 UTC, kjbenk commented on asset-manager.php
> +	 *                           Defaults are 'global', 'single', and 'search'.
Seems like the default is `global` and `single, search` are just supported conditions instead of being part of the default value of the function

2021-10-13 19:34 UTC, kjbenk commented on php/class-asset-manager-svg-sprite.php
> +			$file_contents = file_get_contents( $path ); // phpcs:ignore
VIP has a helper function for this that we should use if available - https://docs.wpvip.com/technical-references/code-quality-and-best-practices/retrieving-remote-data/#h-wpcom_vip_file_get_contents

Also, instead of ignoring all phpcs warnings for this line, we should try to just ignore issues related to `file_get_contents `

2021-10-13 19:34 UTC, kjbenk commented on php/class-asset-manager-svg-sprite.php
> +		echo $this->sprite_document->C14N(); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped
I am still a bit concerned about seeing unescaped data being echoed, even it it is from currently trusted sources. I want to see if there is any way for us to perform even partial escaping.

2021-10-13 19:34 UTC, kjbenk commented on php/class-asset-manager-svg-sprite.php
> +				'width'  => (int) $viewbox_attr[2],
We should check that `$viewbox_attr[2]` is not empty since there is a possibility that viewbox contains malformatted data like `"00 2"` or something :)

2021-10-13 19:34 UTC, kjbenk commented on php/class-asset-manager-svg-sprite.php
> +				'height' => (int) $viewbox_attr[3],
same as above

2021-10-13 19:34 UTC, kjbenk commented on php/class-asset-manager-svg-sprite.php
> +			$asset['attributes'] = array_merge( $asset['attributes'] ?? [], $default_dimensions );
should we return a WP_Error if we could not get width and height attributes?

2021-10-13 19:34 UTC, kjbenk commented on php/class-asset-manager-svg-sprite.php
> +		$local_attrs = array_map( 'esc_attr', $local_attrs );
We should try to escape as late as possible, so in this case we would perform `esc_attr` on the `$value` here - https://github.com/alleyinteractive/wp-asset-manager/pull/23/files#diff-8e5de1a54f5aa5299ace162fe9de050c109eda5ca7d67b64f85f0d96a6d8ddbeR430

2021-10-13 19:34 UTC, kjbenk commented on php/class-asset-manager-svg-sprite.php
> +		if ( ! empty( $asset['attributes']['width'] ) && ! empty( $asset['attributes']['height'] ) ) {
Again, should we return an error if we cannot parse the width and height?

2021-10-13 19:34 UTC, kjbenk commented on php/traits/trait-conditions.php
> +		if ( ! isset( static::$_conditions ) || ( defined( 'WP_IRVING_TEST' ) && WP_IRVING_TEST ) ) {
Not a blocker, but can this be a filter instead of an Irving specific constant? Seems odd to put something Irving specific here

2021-10-13 19:34 UTC, kjbenk commented on php/class-asset-manager-svg-sprite.php
> +				$symbol->appendChild( $this->sprite_document->importNode( $child_node, true ) );
Will this account for grandchild nodes and beyond?

2021-10-13 19:34 UTC, kjbenk commented on php/class-asset-manager-svg-sprite.php
> +			$symbol->appendChild( $symbol_viewbox );
Is this essentially adding an attribute? Seems weird to use `appendChild` for adding an attribute.

2021-10-13 19:34 UTC, kjbenk commented on php/class-asset-manager-svg-sprite.php
> +		echo $this->sprite_document->C14N(); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped
Is there a specific reason why we cannot escape this like we are here? - https://github.com/alleyinteractive/wp-asset-manager/pull/23/files#diff-8e5de1a54f5aa5299ace162fe9de050c109eda5ca7d67b64f85f0d96a6d8ddbeR450

2021-10-13 19:34 UTC, kjbenk commented on php/class-asset-manager-svg-sprite.php
> +				&& 'script' !== $child_node->nodeName // Exclude <script> tags.
nice :)

2021-10-13 19:34 UTC, kjbenk commented on tests/test-sprite.php
> +			$this->with_embedded_script
Should this be called `without_embedded_script` since this assumes the script is not embedded?

2021-10-13 19:53 UTC, goodguyry commented on php/class-asset-manager-svg-sprite.php
> +		$local_attrs = array_map( 'esc_attr', $local_attrs );
I ripped both of these straight from core.
https://core.trac.wordpress.org/browser/tags/5.8/src/wp-includes/media.php#L1092

2021-10-13 21:55 UTC, goodguyry commented on php/traits/trait-conditions.php
> +		if ( ! isset( static::$_conditions ) || ( defined( 'WP_IRVING_TEST' ) && WP_IRVING_TEST ) ) {
[That code predates this PR](https://github.com/alleyinteractive/wp-asset-manager/pull/11/commits/14ad036b013d3f92e6efb94eb8468de77b1d7880), so I'd rather leave it for now.

2021-10-13 21:57 UTC, goodguyry commented on php/class-asset-manager-svg-sprite.php
> +			$symbol->appendChild( $symbol_viewbox );
https://www.php.net/manual/en/domdocument.createattribute.php
> This function creates a new instance of class DOMAttr. This node will not show up in the document unless it is inserted with (e.g.) DOMNode::appendChild().

2021-10-13 23:08 UTC, goodguyry commented on tests/test-sprite.php
> +			$this->with_embedded_script
🤷  It's the expected output from a SVG file _with_ an embedded script tag

2021-10-13 23:11 UTC, goodguyry commented on php/class-asset-manager-svg-sprite.php
> +			$asset['attributes'] = array_merge( $asset['attributes'] ?? [], $default_dimensions );
It's not an error per se, but just means the developer will have to be explicit about the desired size when printing it to the page. I updated the documentation to (hopefully) make this more clear.

2021-10-13 23:12 UTC, goodguyry commented on php/class-asset-manager-svg-sprite.php
> +				$symbol->appendChild( $this->sprite_document->importNode( $child_node, true ) );
Yep. I added a test to be sure.

2021-10-13 23:14 UTC, goodguyry commented on php/class-asset-manager-svg-sprite.php
> +				'width'  => (int) $viewbox_attr[2],
If the `viewBox` attribute is malformed they've got bigger problems :) But I take your point that it's best to check for the values before saving 👍

2021-10-13 23:15 UTC, goodguyry commented on README.md
> +am_define_symbol(
I added a note :)

2021-10-13 23:15 UTC, goodguyry commented on README.md
> +The [wp_body_open()](https://developer.wordpress.org/reference/functions/wp_body_open/) function is required for the sprite sheet to print to the template.
I updated the documentation to clean this up

2021-10-13 23:16 UTC, goodguyry commented on asset-manager.php
> +	 *                           Defaults are 'global', 'single', and 'search'.
Good thought. I changed it to say that `'global'` is assumed if there's no `condition`

2021-10-13 23:29 UTC, goodguyry commented on php/class-asset-manager-svg-sprite.php
> +		echo $this->sprite_document->C14N(); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped
🤔  I supposed we could collect elements and attributes as they're added to the sprite. I hadn't considered that, but it seems like it would solve this issue.

2021-10-13 23:31 UTC, goodguyry commented on php/class-asset-manager-svg-sprite.php
> +			$file_contents = file_get_contents( $path ); // phpcs:ignore
Cool, thanks. Thanks also for catching the global ignore. I meant to go through and make those more explicit.

2021-10-13 23:42 UTC, goodguyry commented on php/class-asset-manager-svg-sprite.php
> +		echo $this->sprite_document->C14N(); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped
We've also got unescaped content in the scripts and styles `inline` load method, FWIW. Not sure how to clean those up.

2021-10-15 00:03 UTC, goodguyry commented on php/class-asset-manager-svg-sprite.php
> +			$symbol->appendChild( $symbol_viewbox );
Your intuition was correct. I just noticed the `setAttribute` method on [DOMElement](https://www.php.net/manual/en/class.domelement.php).

2022-09-20 18:10 UTC, srtfisher approved these changes
all looks great! a wonderful feature 😄

2022-09-20 18:10 UTC, srtfisher commented on README.md
> +* PHP: 7.1+
I'd argue to bump to 7.4 for our sanity and to mirror what we're testing against in CI.

2022-09-28 18:49 UTC, merged